name: V2Ray Config Collector

on:
  schedule:
    - cron: '0 * * * *'  # Запускать раз в час
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect_configs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 pydantic jdatetime aiofiles rich  # Убраны лишние зависимости

      - name: Run script
        run: |
          python main.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "action@github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "🔄 Update V2Ray configs on $(TZ='Asia/Tehran' date)"
            git push
          else
            echo "No changes to commit."
          fi
